name: Deploy Nuxt site to GitHub Pages

on:
  # 在针对 `master` 分支的推送时运行。根据你的主分支名称修改。
  push:
    branches: ["master"]

  # 允许你从 Actions 页签手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和等待队列中的运行之间的构建
# 但是，不要取消进行中的运行，因为我们希望允许完成部署
concurrency:
  group: "pages"
  cancel-in-progress: false # 设置为 false 以允许旧部署完成

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # 启用 corepack 来管理 pnpm 版本 (如果 package.json 中指定了)
      - name: Enable Corepack
        run: corepack enable
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # 选择你项目所需的 Node.js 版本
          cache: 'pnpm' # 如果你使用 npm，改为 'npm'
          # cache-dependency-path: yarn.lock # 可选，如果锁文件不在根目录
      - name: Install Dependencies
        run: pnpm install # 如果你使用 npm，改为 npm install
      - name: Build with Nuxt Preset (Nuxt 3)
        # 如果你的 baseURL 是动态设置或未在 nuxt.config.ts 中固定，可以在这里通过环境变量设置
        # 将 <repository-name> 替换成你的仓库名，如果不需要 baseURL 则删除 env 部分
        run: npx nuxt build --preset github_pages
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
        #   NUXT_APP_BASE_URL: /<repository-name>/
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        # 如果 nuxt.config.ts 中没有设置 baseURL，且你需要设置，可以在这里配置
        # with:
        #   base: '/<repository-name>/'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Nuxt 3 的生成目录默认为 .output/public
          # 如果是 Nuxt 2，通常是 'dist'
          path: '.output/public'

  # 部署任务
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
